; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:test]
platform = native
lib_deps = 
	tomstewart89/BasicLinearAlgebra@^5.1
	greiman/SdFat@^2.3.1
	; stm32duino/STM32duino LSM6DSO@^2.2.0
framework = 
test_build_src = true

[env]
platform = ststm32
framework = arduino

[env:mars]
board = mars
board_build.variants_dir = variants
build_flags = 
	-D MARS
	-I variants/MARS
	-DTIM_IRQ_PRIO=2
	-DTIM_I2C_PRIO=3
	-DPIO_FRAMEWORK_ARDUINO_ENABLE_CDC
	-DUSBCON
	-DUSBD_VID=0
	-DUSBD_PID=0
	-DHSE_BYPASS_NOT_USED
	-DLSE_BYPASS_NOT_USED
	-Wa,-mfloat-abi=hard
	-Wa,-mfpu=fpv4-sp-d16
	-O3
upload_protocol = dfu
lib_deps = 
	stm32duino/STM32duino ASM330LHH@^2.0.1
	Wire
	SPI
	; stm32duino/STM32duino LSM6DSO@^2.2.0
