; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
boards_dir = board/boards

[env:marsv20]
platform = ststm32
framework = arduino
board = marsv20
board_build.variants_dir = board/variants
lib_deps = 
	stm32duino/STM32duino LSM6DSO@^2.2.0
	stm32duino/STM32duino ASM330LHH@^2.0.1
	stm32duino/STM32duino LIS2MDL@^2.0.1
	stm32duino/STM32duino LPS22HB@^2.0.0
	stm32duino/STM32duino LSM6DSO32@^1.0.0
